# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0.xci
# IP: The module: 'mp0_rst_mp0_25M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0.xci
# IP: The module: 'mp0_rst_mp0_25M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-0/hw/hdl/mp0/ip/mp0_rst_mp0_25M_0/mp0_rst_mp0_25M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp0_rst_mp0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
